#!/command/with-contenv bash
# shellcheck shell=bash

# copy local php.ini if it doesn't exist
if [[ ! -f /config/php/php-local.ini ]]; then
    cp /defaults/php/php-local.ini /config/php/php-local.ini
    sed -i \
        -e "s|date.timezone = UTC|date.timezone = $TZ|g" \
        /config/php/php-local.ini
fi

# copy user php-local.ini to image
cp /config/php/php-local.ini /etc/php"$PHP_VERSION"/conf.d/php-local.ini

# create override for www.conf if it doesn't exist
if [[ ! -f /config/php/www2.conf ]]; then
    cp /defaults/php/www2.conf /config/php/www2.conf
fi

# copy user www2.conf to image
cp /config/php/www2.conf /etc/php"$PHP_VERSION"/php-fpm.d/www2.conf