#!/command/with-contenv bash
# shellcheck shell=bash

SUBJECT="/C=ID/ST=CGK/L=Jakarta/O=*/OU=*/CN=*"
if [[ -f /config/ssl/cert.key && -f /config/ssl/cert.crt ]]; then
    echo "==> Ssl certificate available"
else
    echo "==> Create self-signed cert in /config/ssl, replace these with your own ssl if required"
    rm -f \
        /config/ssl/cert.key \
        /config/ssl/cert.crt || true
    openssl req -new -x509 -days 3650 -nodes -out /config/ssl/cert.crt -keyout /config/ssl/cert.key -subj "$SUBJECT"
fi
