#!/command/with-contenv bash
# shellcheck shell=bash

# remove old samples
find /config/nginx/samples \
    -name "*.conf.sample" \
    -type f \
    -delete

# copy new samples
find /defaults/nginx/samples \
    -maxdepth 1 \
    -name "*.conf.sample" \
    -type f \
    -exec cp "{}" /config/nginx/samples +