#!/command/with-contenv bash
# shellcheck shell=bash

# permissions
chown -R disty:disty \
    /var/lib/nginx \
    /var/tmp/nginx

chown -R disty:disty \
    /config/ssl \
    /config/nginx \
    /config/php

chown -R disty:disty \
    /config/www \
    /config/log

chmod -R g+w \
    /config/nginx

chmod -R 644 /etc/logrotate.d

if [[ -f "/config/log/logrotate.status" ]]; then
    chmod 600 /config/log/logrotate.status
fi